[package]
authors = ["Kornel <pornel@pornel.net>"]
build = "src/build.rs"
description = "API for the DSSIM tool. AGPL-licensed. Measures structural similarity between images using a multi-scale variant of the SSIM algorithm."
documentation = "https://github.com/pornel/dssim"
keywords = ["ssim", "image", "comparison"]
license = "AGPL-3.0"
name = "dssim"
repository = "https://github.com/pornel/dssim2.git"
version = "2.3.0"

[[bin]]
doctest = false
name = "dssim"
path = "src/main.rs"

[dependencies]
c_vec = "= 1.0.12"
getopts = "0.2.4"
itertools = "0.4.4"
lcms2 = "1.0.0"
libc = "0.2.4"
lodepng = "0.6.2"
rgb = "0.2.0"
unzip3 = "0.1.0"

[dependencies.mozjpeg]
path = "../mozjpeg-rust"

[lib]
doctest = false
name = "dssim"
